### ISSUE TITLE
Import privkey (rescanning) is incredibly slow.

### ISSUE THREAD

**Issue by NStal** [lavaio/lava#43]
Import privkey with scanning is incredibly slow.

Import should be processed within minutes with only thousands of blocks.

Import takes more than half an hour, and my computer randomly stop 

## How reliably can you reproduce the issue, what are the steps to do so? 
`importprivkey <privkey> <name>true`

Win32

**Comment by kbroflovski21** [comment]
Importing private key(s) asks for scanning and verifying processes for historical transactions, not just block headers. This makes importing private key(s) much more time-consuming than downloading blocks. In the future we also consider some solutions to speed up the process, like starting verify TXs from a specific height halfway.
