### ISSUE TITLE
Do we have a bip44 coin_type code?

### ISSUE THREAD

**Issue by NStal** [lavaio/lava#45]
Do we have a bip44 coin_type code registered according to https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki ?

Considering lava's longterm ambition. If we don't have one, we should as soon as possible.

**Comment by HarvestStars** [comment]
Lava will make a coin_type pullrequest into SLIP-0044 soon in days.

**Comment by HarvestStars** [comment]
it has been done
